### ISSUE TITLE
Cannot read property "snipet" of undefined

### ISSUE THREAD

**Issue by TsundereDoge** [HyperCoder2975/simple-youtube-api#9]
Hi,

First of all thx for this awesome library! ^^
Everything was working but with some playlist I get this error:

`TypeError: Cannot read property 'snippet' of undefined
    at new Video (C:\Users\TsunDoge\Documents\RepositoriosGit\kerberosbot\node_modules\simple-youtube-api\src\structures\Video.js:29:23)
    at request.then.result (C:\Users\TsunDoge\Documents\RepositoriosGit\kerberosbot\node_modules\simple-youtube-api\src\YouTube.js:72:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Uncaught Promise Error:  TypeError: Cannot read property 'durationSeconds' of undefined
    at handlePlaylist (C:\Users\TsunDoge\Documents\RepositoriosGit\kerberosbot\commands\play.js:131:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

This happens when I'm getting a video by ID:
`const video2 = await youtube.getVideoByID(video.id).catch(error => console.log(error));`

Maybe I'm doing something wrong when trying to add the videos once I have all the videos of the playlist.

TsunDoge

**Comment by DoctorDarkMagic** [comment]
I too am having this issue.

**Comment by GitStonic** [comment]
mee three

**Comment by ApolloMason** [comment]
Same here

**Comment by ApolloMason** [comment]
It seems like they dont even care tho tbf

**Comment by appellation** [comment]
fixed in v4
